package com.enterprise.taskmanager.model;

/*
 * ============================================================
 * USER MODEL — Represents a User in our Database
 * ============================================================
 *
 * WHAT IS THIS?
 * This class stores user information for authentication (login/register).
 * Each user has a username, password, and a role (USER or ADMIN).
 *
 * WHY DO WE NEED THIS?
 * For security! We need to know WHO is making API requests.
 * Without this, anyone could access or delete any data.
 *
 * ============================================================
 */

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

// Store objects of this class in a MongoDB collection called "users"
@Document(collection = "users")
public class User {

    // ---- FIELDS ----

    // Unique identifier (auto-generated by MongoDB)
    @Id
    private String id;

    // The username (must be unique — @Indexed(unique = true) enforces this)
    // @Indexed tells MongoDB to create an "index" for fast lookups
    @Indexed(unique = true)
    private String username;

    // The password (stored as a HASH, never plain text!)
    // Hashing = converting "password123" into something like "$2a$10$xR3..."
    // This way, even if the database is hacked, passwords are safe.
    private String password;

    // The user's role: "ROLE_USER" or "ROLE_ADMIN"
    // Roles control what a user is ALLOWED to do (Authorization)
    private String role;

    // ---- CONSTRUCTORS ----

    // Default constructor (required by Spring/MongoDB)
    public User() {
    }

    // Parameterized constructor — a shortcut to create a User with all fields
    public User(String username, String password, String role) {
        this.username = username;
        this.password = password;
        this.role = role;
    }

    // ---- GETTERS AND SETTERS ----

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public String toString() {
        // NOTE: We never print the password for security reasons!
        return "User{" +
                "id='" + id + '\'' +
                ", username='" + username + '\'' +
                ", role='" + role + '\'' +
                '}';
    }
}
